# Seed data for Abqour (عبقور) — categories, games, achievements, questions, words.

CATEGORIES = [
    {"key": "science", "name_ar": "علوم", "icon": "flask", "color": "#10B981"},
    {"key": "tech", "name_ar": "تقنية", "icon": "cpu", "color": "#3B82F6"},
    {"key": "history", "name_ar": "تاريخ", "icon": "book", "color": "#F59E0B"},
    {"key": "geography", "name_ar": "جغرافيا", "icon": "globe", "color": "#06B6D4"},
    {"key": "sports", "name_ar": "رياضة", "icon": "activity", "color": "#EF4444"},
    {"key": "culture", "name_ar": "ثقافة عامة", "icon": "award", "color": "#8B5CF6"},
    {"key": "iq", "name_ar": "ذكاء", "icon": "zap", "color": "#EC4899"},
    {"key": "riddles", "name_ar": "ألغاز", "icon": "help-circle", "color": "#F5B301"},
]

GAMES = [
    {
        "key": "quiz",
        "title_ar": "كويز المعلومات",
        "description_ar": "أجب على الأسئلة واختبر معلوماتك في مختلف المجالات، واجمع أكبر عدد من النقاط قبل انتهاء الوقت!",
        "status": "active",
        "gradient": ["#F97316", "#EF4444"],
        "icon": "help-circle",
        "rating": 4.8,
        "plays_count": 15200,
        "tag": "featured",
        "order": 1,
        "multiplayer": True,
    },
    {
        "key": "puzzle",
        "title_ar": "تركيب الصور",
        "description_ar": "أعد ترتيب قطع الصورة المبعثرة لتكوين الصورة الأصلية في أقل عدد من الحركات.",
        "status": "active",
        "gradient": ["#8B5CF6", "#EC4899"],
        "icon": "image",
        "rating": 4.6,
        "plays_count": 9800,
        "tag": "featured",
        "order": 2,
        "multiplayer": False,
    },
    {
        "key": "word",
        "title_ar": "تركيب الكلمات",
        "description_ar": "رتّب الحروف المبعثرة لتكوين الكلمة الصحيحة قبل انتهاء الوقت.",
        "status": "active",
        "gradient": ["#14B8A6", "#059669"],
        "icon": "type",
        "rating": 4.7,
        "plays_count": 11300,
        "tag": "featured",
        "order": 3,
        "multiplayer": False,
    },
    {"key": "speed", "title_ar": "سرعة الإجابة", "description_ar": "أجب بأسرع ما يمكن!", "status": "coming_soon", "gradient": ["#6366F1", "#8B5CF6"], "icon": "zap", "rating": 0, "plays_count": 0, "tag": "upcoming", "order": 10, "multiplayer": False},
    {"key": "guess_image", "title_ar": "احزر الصورة", "description_ar": "خمّن الصورة الغامضة.", "status": "coming_soon", "gradient": ["#F59E0B", "#F97316"], "icon": "eye", "rating": 0, "plays_count": 0, "tag": "upcoming", "order": 11, "multiplayer": False},
    {"key": "find_diff", "title_ar": "اكتشف الفرق", "description_ar": "اعثر على الفروقات بين الصورتين.", "status": "coming_soon", "gradient": ["#06B6D4", "#3B82F6"], "icon": "search", "rating": 0, "plays_count": 0, "tag": "upcoming", "order": 12, "multiplayer": False},
    {"key": "memory", "title_ar": "الذاكرة", "description_ar": "طابق البطاقات المتشابهة.", "status": "coming_soon", "gradient": ["#EC4899", "#8B5CF6"], "icon": "grid", "rating": 0, "plays_count": 0, "tag": "upcoming", "order": 13, "multiplayer": False},
    {"key": "xo", "title_ar": "X-O", "description_ar": "لعبة إكس-أو الكلاسيكية.", "status": "coming_soon", "gradient": ["#10B981", "#14B8A6"], "icon": "hash", "rating": 0, "plays_count": 0, "tag": "upcoming", "order": 14, "multiplayer": True},
]

ACHIEVEMENTS = [
    {"key": "first_game", "title_ar": "أول خطوة", "description_ar": "أكمل أول لعبة لك", "icon": "flag", "xp": 50, "target": 1, "metric": "games_played"},
    {"key": "quiz_master", "title_ar": "خبير الكويز", "description_ar": "العب 10 جولات كويز", "icon": "help-circle", "xp": 150, "target": 10, "metric": "quiz_plays"},
    {"key": "level_5", "title_ar": "المستوى الخامس", "description_ar": "اوصل للمستوى 5", "icon": "trending-up", "xp": 200, "target": 5, "metric": "level"},
    {"key": "score_1000", "title_ar": "جامع النقاط", "description_ar": "اجمع 1000 نقطة", "icon": "star", "xp": 100, "target": 1000, "metric": "total_score"},
    {"key": "perfect_quiz", "title_ar": "الإجابة المثالية", "description_ar": "أجب على كل أسئلة جولة بشكل صحيح", "icon": "check-circle", "xp": 250, "target": 1, "metric": "perfect_quiz"},
    {"key": "puzzle_solver", "title_ar": "حلّال الألغاز", "description_ar": "أكمل 5 صور", "icon": "image", "xp": 150, "target": 5, "metric": "puzzle_plays"},
    {"key": "word_wizard", "title_ar": "ساحر الكلمات", "description_ar": "كوّن 20 كلمة", "icon": "type", "xp": 180, "target": 20, "metric": "words_solved"},
    {"key": "streak_3", "title_ar": "متواصل", "description_ar": "العب 3 أيام متتالية", "icon": "calendar", "xp": 120, "target": 3, "metric": "day_streak"},
]

# Arabic words for the word-assembly game (word, hint)
WORDS = [
    {"word": "كتاب", "hint": "تقرأ فيه"},
    {"word": "مدرسة", "hint": "مكان للتعلم"},
    {"word": "شمس", "hint": "تشرق نهاراً"},
    {"word": "قمر", "hint": "يظهر ليلاً"},
    {"word": "بحر", "hint": "ماء واسع مالح"},
    {"word": "جبل", "hint": "مرتفع من الأرض"},
    {"word": "زهرة", "hint": "نبات جميل عطر"},
    {"word": "سيارة", "hint": "وسيلة نقل"},
    {"word": "طائرة", "hint": "تطير في السماء"},
    {"word": "حاسوب", "hint": "جهاز إلكتروني"},
    {"word": "هاتف", "hint": "للاتصال"},
    {"word": "قلم", "hint": "أداة للكتابة"},
    {"word": "نافذة", "hint": "فتحة في الجدار"},
    {"word": "حديقة", "hint": "مكان أخضر للنزهة"},
    {"word": "مطر", "hint": "ماء ينزل من السماء"},
    {"word": "عصفور", "hint": "طائر صغير"},
    {"word": "برتقال", "hint": "فاكهة حمضية"},
    {"word": "تفاح", "hint": "فاكهة حمراء"},
    {"word": "قطار", "hint": "يسير على سكة"},
    {"word": "مفتاح", "hint": "يفتح الباب"},
]

# Trivia questions: category key, text, options (4), correct index, difficulty
QUESTIONS = [
    # science
    {"category": "science", "text": "ما هو أكبر كوكب في المجموعة الشمسية؟", "options": ["المشتري", "زحل", "الأرض", "المريخ"], "correct": 0, "difficulty": "easy"},
    {"category": "science", "text": "ما هو العنصر الكيميائي الذي رمزه O؟", "options": ["الذهب", "الأكسجين", "الحديد", "الكربون"], "correct": 1, "difficulty": "easy"},
    {"category": "science", "text": "كم عدد عظام جسم الإنسان البالغ؟", "options": ["206", "150", "300", "180"], "correct": 0, "difficulty": "medium"},
    {"category": "science", "text": "ما هي سرعة الضوء تقريباً؟", "options": ["300 ألف كم/ث", "150 ألف كم/ث", "1000 كم/ث", "مليون كم/ث"], "correct": 0, "difficulty": "medium"},
    {"category": "science", "text": "ما الغاز الذي تحتاجه النباتات في عملية البناء الضوئي؟", "options": ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], "correct": 2, "difficulty": "easy"},
    {"category": "science", "text": "ما هو أقرب كوكب إلى الشمس؟", "options": ["الزهرة", "عطارد", "الأرض", "المريخ"], "correct": 1, "difficulty": "easy"},
    {"category": "science", "text": "ما العضو المسؤول عن ضخ الدم في الجسم؟", "options": ["الكبد", "الرئة", "القلب", "الكلى"], "correct": 2, "difficulty": "easy"},
    {"category": "science", "text": "ما هي وحدة قياس القوة؟", "options": ["الجول", "النيوتن", "الواط", "الأمبير"], "correct": 1, "difficulty": "medium"},
    {"category": "science", "text": "كم عدد كروموسومات الإنسان الطبيعي؟", "options": ["44", "46", "48", "23"], "correct": 1, "difficulty": "hard"},
    {"category": "science", "text": "ما المعدن الأكثر توصيلاً للكهرباء؟", "options": ["النحاس", "الفضة", "الذهب", "الحديد"], "correct": 1, "difficulty": "hard"},
    # tech
    {"category": "tech", "text": "ماذا يعني اختصار CPU؟", "options": ["وحدة المعالجة المركزية", "ذاكرة الوصول العشوائي", "القرص الصلب", "بطاقة الرسوميات"], "correct": 0, "difficulty": "easy"},
    {"category": "tech", "text": "من أسّس شركة مايكروسوفت؟", "options": ["ستيف جوبز", "بيل جيتس", "مارك زوكربيرغ", "إيلون ماسك"], "correct": 1, "difficulty": "easy"},
    {"category": "tech", "text": "ما لغة البرمجة التي تُستخدم أساساً في تطوير الويب للواجهة؟", "options": ["بايثون", "جافاسكريبت", "سي++", "جافا"], "correct": 1, "difficulty": "medium"},
    {"category": "tech", "text": "ماذا يعني HTTP؟", "options": ["بروتوكول نقل النص التشعبي", "نظام تشغيل", "لغة برمجة", "نوع ذاكرة"], "correct": 0, "difficulty": "medium"},
    {"category": "tech", "text": "ما الشركة المطوّرة لنظام أندرويد؟", "options": ["آبل", "جوجل", "مايكروسوفت", "سامسونج"], "correct": 1, "difficulty": "easy"},
    {"category": "tech", "text": "كم بايت في الكيلوبايت الواحد؟", "options": ["1000", "1024", "512", "2048"], "correct": 1, "difficulty": "medium"},
    {"category": "tech", "text": "ما اسم أول حاسوب إلكتروني رقمي؟", "options": ["ENIAC", "IBM PC", "Apple I", "Altair"], "correct": 0, "difficulty": "hard"},
    {"category": "tech", "text": "ماذا يعني AI؟", "options": ["الذكاء الاصطناعي", "الإنترنت المتقدم", "واجهة التطبيق", "المعلومات الآلية"], "correct": 0, "difficulty": "easy"},
    {"category": "tech", "text": "ما البروتوكول المسؤول عن عناوين المواقع الآمنة؟", "options": ["FTP", "HTTPS", "SMTP", "SSH"], "correct": 1, "difficulty": "medium"},
    {"category": "tech", "text": "من مؤسس شركة تسلا وسبيس إكس؟", "options": ["جيف بيزوس", "إيلون ماسك", "لاري بيج", "بيل جيتس"], "correct": 1, "difficulty": "easy"},
    # history
    {"category": "history", "text": "في أي عام بدأت الحرب العالمية الأولى؟", "options": ["1914", "1939", "1918", "1905"], "correct": 0, "difficulty": "medium"},
    {"category": "history", "text": "من هو أول خليفة للمسلمين؟", "options": ["عمر بن الخطاب", "أبو بكر الصديق", "عثمان بن عفان", "علي بن أبي طالب"], "correct": 1, "difficulty": "easy"},
    {"category": "history", "text": "من بنى الأهرامات؟", "options": ["الرومان", "الإغريق", "المصريون القدماء", "البابليون"], "correct": 2, "difficulty": "easy"},
    {"category": "history", "text": "في أي عام سقطت الأندلس (غرناطة)؟", "options": ["1492", "1453", "1258", "1099"], "correct": 0, "difficulty": "hard"},
    {"category": "history", "text": "من هو القائد الذي فتح القسطنطينية؟", "options": ["صلاح الدين", "محمد الفاتح", "خالد بن الوليد", "طارق بن زياد"], "correct": 1, "difficulty": "medium"},
    {"category": "history", "text": "من هو مكتشف قارة أمريكا؟", "options": ["ماجلان", "كولومبوس", "فاسكو دي جاما", "ماركو بولو"], "correct": 1, "difficulty": "easy"},
    {"category": "history", "text": "في أي عام انتهت الحرب العالمية الثانية؟", "options": ["1945", "1939", "1918", "1950"], "correct": 0, "difficulty": "medium"},
    {"category": "history", "text": "من هو القائد الذي عبر جبال الألب بالفيلة؟", "options": ["يوليوس قيصر", "هانيبال", "الإسكندر", "نابليون"], "correct": 1, "difficulty": "hard"},
    {"category": "history", "text": "من هو مؤسس الدولة السعودية الأولى؟", "options": ["الملك عبدالعزيز", "الإمام محمد بن سعود", "الملك سعود", "الملك فيصل"], "correct": 1, "difficulty": "medium"},
    {"category": "history", "text": "أين قامت حضارة بلاد الرافدين؟", "options": ["مصر", "العراق", "اليمن", "الشام"], "correct": 1, "difficulty": "medium"},
    # geography
    {"category": "geography", "text": "ما هي عاصمة اليابان؟", "options": ["بكين", "طوكيو", "سيول", "بانكوك"], "correct": 1, "difficulty": "easy"},
    {"category": "geography", "text": "ما هو أطول نهر في العالم؟", "options": ["النيل", "الأمازون", "المسيسيبي", "اليانغتسي"], "correct": 0, "difficulty": "medium"},
    {"category": "geography", "text": "في أي قارة تقع مصر؟", "options": ["آسيا", "أفريقيا", "أوروبا", "أستراليا"], "correct": 1, "difficulty": "easy"},
    {"category": "geography", "text": "ما هي أكبر دولة في العالم مساحةً؟", "options": ["الصين", "روسيا", "كندا", "أمريكا"], "correct": 1, "difficulty": "easy"},
    {"category": "geography", "text": "ما هي عاصمة أستراليا؟", "options": ["سيدني", "كانبرا", "ملبورن", "بيرث"], "correct": 1, "difficulty": "hard"},
    {"category": "geography", "text": "ما أكبر محيط في العالم؟", "options": ["الأطلسي", "الهندي", "الهادئ", "المتجمد"], "correct": 2, "difficulty": "easy"},
    {"category": "geography", "text": "ما هي عاصمة المملكة العربية السعودية؟", "options": ["جدة", "الرياض", "مكة", "الدمام"], "correct": 1, "difficulty": "easy"},
    {"category": "geography", "text": "ما أعلى قمة جبلية في العالم؟", "options": ["كي 2", "إيفرست", "كليمنجارو", "المونت بلانك"], "correct": 1, "difficulty": "easy"},
    {"category": "geography", "text": "ما هي أصغر قارة في العالم؟", "options": ["أوروبا", "أستراليا", "أنتاركتيكا", "أمريكا الجنوبية"], "correct": 1, "difficulty": "medium"},
    {"category": "geography", "text": "أي دولة تُعرف بأرض الشمس المشرقة؟", "options": ["الصين", "اليابان", "كوريا", "تايلاند"], "correct": 1, "difficulty": "medium"},
    # sports
    {"category": "sports", "text": "كم عدد لاعبي فريق كرة القدم في الملعب؟", "options": ["10", "11", "12", "9"], "correct": 1, "difficulty": "easy"},
    {"category": "sports", "text": "كل كم سنة تقام بطولة كأس العالم لكرة القدم؟", "options": ["سنتان", "ثلاث سنوات", "أربع سنوات", "خمس سنوات"], "correct": 2, "difficulty": "easy"},
    {"category": "sports", "text": "ما الرياضة المرتبطة باسم مايكل جوردان؟", "options": ["كرة القدم", "كرة السلة", "التنس", "الجولف"], "correct": 1, "difficulty": "easy"},
    {"category": "sports", "text": "أي دولة فازت بأول كأس عالم لكرة القدم عام 1930؟", "options": ["البرازيل", "الأوروغواي", "الأرجنتين", "إيطاليا"], "correct": 1, "difficulty": "hard"},
    {"category": "sports", "text": "كم عدد الحلقات في شعار الأولمبياد؟", "options": ["4", "5", "6", "3"], "correct": 1, "difficulty": "medium"},
    {"category": "sports", "text": "في أي رياضة يُستخدم مصطلح 'love' للدلالة على الصفر؟", "options": ["التنس", "الجولف", "الكريكيت", "الاسكواش"], "correct": 0, "difficulty": "medium"},
    {"category": "sports", "text": "من هو اللاعب الملقب بـ'الأسطورة' في كرة القدم الأرجنتينية؟", "options": ["ميسي", "مارادونا", "بيليه", "رونالدو"], "correct": 1, "difficulty": "medium"},
    {"category": "sports", "text": "كم شوطاً في مباراة كرة القدم؟", "options": ["1", "2", "3", "4"], "correct": 1, "difficulty": "easy"},
    # culture
    {"category": "culture", "text": "كم عدد ألوان قوس قزح؟", "options": ["5", "6", "7", "8"], "correct": 2, "difficulty": "easy"},
    {"category": "culture", "text": "ما أطول سورة في القرآن الكريم؟", "options": ["البقرة", "آل عمران", "النساء", "الأنعام"], "correct": 0, "difficulty": "easy"},
    {"category": "culture", "text": "من كتب مسرحية روميو وجولييت؟", "options": ["شكسبير", "تولستوي", "ديكنز", "همنغواي"], "correct": 0, "difficulty": "medium"},
    {"category": "culture", "text": "ما عدد أيام السنة الميلادية العادية؟", "options": ["365", "366", "364", "360"], "correct": 0, "difficulty": "easy"},
    {"category": "culture", "text": "ما اللغة الأكثر تحدثاً في العالم كلغة أم؟", "options": ["الإنجليزية", "الصينية", "الإسبانية", "العربية"], "correct": 1, "difficulty": "medium"},
    {"category": "culture", "text": "كم عدد أركان الإسلام؟", "options": ["4", "5", "6", "3"], "correct": 1, "difficulty": "easy"},
    {"category": "culture", "text": "ما عاصمة الثقافة القديمة والفن في إيطاليا؟", "options": ["ميلانو", "روما", "البندقية", "فلورنسا"], "correct": 3, "difficulty": "hard"},
    {"category": "culture", "text": "من رسم لوحة الموناليزا؟", "options": ["بيكاسو", "دافنشي", "فان غوخ", "مايكل أنجلو"], "correct": 1, "difficulty": "easy"},
    # iq
    {"category": "iq", "text": "أكمل المتتالية: 2، 4، 8، 16، ؟", "options": ["24", "32", "20", "18"], "correct": 1, "difficulty": "medium"},
    {"category": "iq", "text": "إذا كان 5 عمال يبنون جداراً في 5 أيام، فكم يوماً يحتاج 10 عمال؟", "options": ["2.5", "5", "10", "1"], "correct": 0, "difficulty": "hard"},
    {"category": "iq", "text": "ما العدد الذي يأتي بعد: 1، 1، 2، 3، 5، 8، ؟", "options": ["11", "13", "12", "10"], "correct": 1, "difficulty": "medium"},
    {"category": "iq", "text": "أكمل: 3، 6، 9، 12، ؟", "options": ["14", "15", "16", "18"], "correct": 1, "difficulty": "easy"},
    {"category": "iq", "text": "كم مثلثاً في نجمة خماسية بسيطة؟", "options": ["5", "10", "8", "6"], "correct": 0, "difficulty": "hard"},
    {"category": "iq", "text": "إذا كان اليوم الثلاثاء، فما اليوم بعد 100 يوم؟", "options": ["الخميس", "الجمعة", "الأربعاء", "السبت"], "correct": 0, "difficulty": "hard"},
    {"category": "iq", "text": "ما ناتج: نصف الثلث لعدد 60؟", "options": ["10", "20", "30", "15"], "correct": 0, "difficulty": "medium"},
    {"category": "iq", "text": "أكمل النمط: أ، ج، هـ، ؟", "options": ["و", "ز", "ح", "ط"], "correct": 1, "difficulty": "medium"},
    # riddles
    {"category": "riddles", "text": "شيء كلما أخذت منه كبر، فما هو؟", "options": ["الحفرة", "البالون", "النهر", "الشمعة"], "correct": 0, "difficulty": "medium"},
    {"category": "riddles", "text": "له أوراق وليس بنبات، فما هو؟", "options": ["الشجرة", "الكتاب", "الزهرة", "الريح"], "correct": 1, "difficulty": "easy"},
    {"category": "riddles", "text": "يمشي بلا رجلين ويبكي بلا عينين، فما هو؟", "options": ["الطفل", "السحاب", "النهر", "الريح"], "correct": 1, "difficulty": "medium"},
    {"category": "riddles", "text": "بيت بلا أبواب ولا نوافذ، فما هو؟", "options": ["الكهف", "بيت الشعر", "بيت النحل", "الخيمة"], "correct": 2, "difficulty": "medium"},
    {"category": "riddles", "text": "ما الشيء الذي يكتب ولا يقرأ؟", "options": ["القلم", "الكتاب", "الجريدة", "المعلم"], "correct": 0, "difficulty": "easy"},
    {"category": "riddles", "text": "أخضر في الأرض وأسود في السوق وأحمر في البيت، فما هو؟", "options": ["الطماطم", "الشاي", "الفلفل", "التمر"], "correct": 1, "difficulty": "hard"},
    {"category": "riddles", "text": "شيء يحترق ليعطيك الضوء، فما هو؟", "options": ["المصباح", "الشمعة", "الشمس", "النجم"], "correct": 1, "difficulty": "easy"},
    {"category": "riddles", "text": "له رقبة وليس له رأس، فما هو؟", "options": ["الزرافة", "القميص", "الببغاء", "الحصان"], "correct": 1, "difficulty": "medium"},
]
